/*
 * This file is generated by jOOQ.
 */
package lv.twino.homework.jooq;


import javax.annotation.Generated;

import lv.twino.homework.jooq.tables.Blacklist;
import lv.twino.homework.jooq.tables.LoanRequisition;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_F = Internal.createIndex("PRIMARY_KEY_F", Blacklist.BLACKLIST, new OrderField[] { Blacklist.BLACKLIST.PERSONAL_ID }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", LoanRequisition.LOAN_REQUISITION, new OrderField[] { LoanRequisition.LOAN_REQUISITION.ID }, true);
    }
}
