/*
 * This file is generated by jOOQ.
 */
package lv.twino.homework.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lv.twino.homework.jooq.tables.Blacklist;
import lv.twino.homework.jooq.tables.LoanRequisition;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -144108715;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.BLACKLIST</code>.
     */
    public final Blacklist BLACKLIST = lv.twino.homework.jooq.tables.Blacklist.BLACKLIST;

    /**
     * The table <code>PUBLIC.LOAN_REQUISITION</code>.
     */
    public final LoanRequisition LOAN_REQUISITION = lv.twino.homework.jooq.tables.LoanRequisition.LOAN_REQUISITION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Blacklist.BLACKLIST,
            LoanRequisition.LOAN_REQUISITION);
    }
}
