/*
 * This file is generated by jOOQ.
 */
package lv.twino.homework.jooq;


import javax.annotation.Generated;

import lv.twino.homework.jooq.tables.Blacklist;
import lv.twino.homework.jooq.tables.LoanRequisition;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.BLACKLIST</code>.
     */
    public static final Blacklist BLACKLIST = lv.twino.homework.jooq.tables.Blacklist.BLACKLIST;

    /**
     * The table <code>PUBLIC.LOAN_REQUISITION</code>.
     */
    public static final LoanRequisition LOAN_REQUISITION = lv.twino.homework.jooq.tables.LoanRequisition.LOAN_REQUISITION;
}
