/*
 * This file is generated by jOOQ.
 */
package lv.twino.homework.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanRequisition implements Serializable {

    private static final long serialVersionUID = 2098276165;

    private final Integer    id;
    private final String     name;
    private final String     surname;
    private final String     personalId;
    private final Date       term;
    private final BigDecimal loanAmount;
    private final String     countryCode;

    public LoanRequisition(LoanRequisition value) {
        this.id = value.id;
        this.name = value.name;
        this.surname = value.surname;
        this.personalId = value.personalId;
        this.term = value.term;
        this.loanAmount = value.loanAmount;
        this.countryCode = value.countryCode;
    }

    public LoanRequisition(
        Integer    id,
        String     name,
        String     surname,
        String     personalId,
        Date       term,
        BigDecimal loanAmount,
        String     countryCode
    ) {
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.personalId = personalId;
        this.term = term;
        this.loanAmount = loanAmount;
        this.countryCode = countryCode;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public String getSurname() {
        return this.surname;
    }

    public String getPersonalId() {
        return this.personalId;
    }

    public Date getTerm() {
        return this.term;
    }

    public BigDecimal getLoanAmount() {
        return this.loanAmount;
    }

    public String getCountryCode() {
        return this.countryCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LoanRequisition (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(surname);
        sb.append(", ").append(personalId);
        sb.append(", ").append(term);
        sb.append(", ").append(loanAmount);
        sb.append(", ").append(countryCode);

        sb.append(")");
        return sb.toString();
    }
}
