/*
 * This file is generated by jOOQ.
 */
package lv.twino.homework.jooq.tables.records;


import javax.annotation.Generated;

import lv.twino.homework.jooq.tables.Blacklist;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlacklistRecord extends UpdatableRecordImpl<BlacklistRecord> implements Record1<String> {

    private static final long serialVersionUID = 1198021346;

    /**
     * Setter for <code>PUBLIC.BLACKLIST.PERSONAL_ID</code>.
     */
    public BlacklistRecord setPersonalId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.BLACKLIST.PERSONAL_ID</code>.
     */
    public String getPersonalId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Blacklist.BLACKLIST.PERSONAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPersonalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPersonalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlacklistRecord value1(String value) {
        setPersonalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlacklistRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlacklistRecord
     */
    public BlacklistRecord() {
        super(Blacklist.BLACKLIST);
    }

    /**
     * Create a detached, initialised BlacklistRecord
     */
    public BlacklistRecord(String personalId) {
        super(Blacklist.BLACKLIST);

        set(0, personalId);
    }
}
